# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import store.libs.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20160618_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_number', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('*', 'No specified')], max_length=1)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('alter_phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=20)),
                ('country', models.CharField(default='CANADA', max_length=20)),
                ('profile', models.ImageField(upload_to='client')),
                ('post_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_no', models.CharField(max_length=10)),
                ('branch_no', models.CharField(max_length=10)),
                ('acct_no', store.libs.fields.EncryptedCharField(max_length=64)),
                ('acct_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', store.libs.fields.EncryptedCharField(max_length=256)),
                ('card_holder', models.CharField(max_length=64)),
                ('expired_month', models.IntegerField()),
                ('expired_year', models.IntegerField()),
                ('security_code', models.CharField(max_length=10)),
                ('post_code', models.CharField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_number', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('*', 'No specified')], max_length=1)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('alter_phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=20)),
                ('country', models.CharField(default='CANADA', max_length=20)),
                ('profile', models.ImageField(upload_to='contractor')),
                ('post_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_rule', models.CharField(blank=True, max_length=128)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_product_product', to='store.Product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_product_vendor', to='store.Vendor')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Vendor'),
        ),
    ]
