# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_unit_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('valueType', models.CharField(choices=[('t', 'Text Field'), ('n', 'Numberic Field'), ('s', 'Selection Field')], max_length=1)),
                ('affect_price', models.BooleanField(default=False)),
                ('type_rule', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProductProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.FloatField(blank=True)),
                ('value_select', models.CharField(blank=True, max_length=8)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_rule', models.CharField(blank=True, max_length=128)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_product_property_producttype', to='store.ProductType')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'active'), (2, 'retired')], default=0),
        ),
        migrations.AddField(
            model_name='vendorproductproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_product_property_product', to='store.Product'),
        ),
        migrations.AddField(
            model_name='relatedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='store.Product'),
        ),
        migrations.AddField(
            model_name='relatedproduct',
            name='related_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_related_product', to='store.Product'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_producttype', to='store.Product'),
        ),
    ]
