# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-27 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20160727_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 11, 27, 16, 20, 49, 314427, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='sequence',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 11, 27, 16, 20, 59, 810861, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 11, 27, 16, 21, 10, 341308, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sequence',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 11, 27, 16, 21, 17, 811544, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
