# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20161127_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
