# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-23 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_vendor_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('alter_phone_number', models.CharField(max_length=100)),
                ('shipping_address', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=20)),
                ('country', models.CharField(default=b'CANADA', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('shipping_fee', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Client')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ShoppingCart')),
            ],
        ),
    ]
