# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-23 04:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_shoppingcart_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='created_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 12, 23, 4, 45, 31, 113257, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='status',
            field=models.IntegerField(choices=[(0, b'Open'), (1, b'Pending'), (2, b'Processing'), (3, b'Cancelled'), (4, b'Complete'), (5, b'Shipping'), (6, b'Closed'), (7, b'Unpaid'), (99, b'Error')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='status_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 12, 23, 4, 45, 58, 352123, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
