# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-23 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20161223_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='status_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
