# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-03 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20161223_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='city',
            field=models.CharField(default='Montreal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='post_code',
            field=models.CharField(default='H', max_length=20),
            preserve_default=False,
        ),
    ]
